<?php

namespace App\Helper;
use DB;

class CommonFunction{

    // checking fcm token for force login
    public function fcmCheck($isd,$mobile,$fcmToken)
    {
        $fcmAuth=DB::table('tbl_appUsers')
        ->where([['gcmRegistration',$fcmToken],['isdCode',$isd],['mobileNumber',$mobile]])
        ->first();

        if(!$fcmAuth)
        {
            $result['status']  = "failed";
            $result["message"] = "Unauthorized";
            $result["reason"]  = "Unauthorized FCM Device Token Request";
            $result["code"]    = 401;
            $statusCode        = 401;
            return response()->json($result,$statusCode);
        }
    }


    //our token check, generated by otp
    public function tokenCheck($token,$isd,$mobile)
    {
        $auth=DB::table('tbl_app_users_register')
              ->where([['authToken',$token],['isdCode',$isd],['mobileNumber',$mobile]])
              ->first();

        if(!$auth)
        {
            $result['status']  = "failed";
            $result["message"] = "Unauthorized";
            $result["reason"]  = "Unauthorized token Request";
            $result["code"]    = 401;
            $statusCode        = 401;
            return response()->json($result,$statusCode);

        }

    }

    // parameter checking
    public function parValidation($par,$mess)
    {
        $result['status']="failed";
        $result["message"] ="Data missing: ".$mess." is required";
        $statusCode=400;
        return response()->json($result,$statusCode);
    }


}
